"""
Preset library for 20+ viral caption styles.
Color format in ASS: &HAABBGGRR (Alpha, Blue, Green, Red in Hex)
"""

from typing import Dict, Any, List

CAPTION_PRESETS: Dict[str, Dict[str, Any]] = {
    "viral_yellow": {
        "name": "Viral Yellow Highlight",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H0000FFFF",
        "outline_color": "&H00000000",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Bold white words glowing into bright yellow for maximum engagement.",
    },
    "neon_green": {
        "name": "Neon Green Pop",
        "font_name": "Impact",
        "font_size": 42,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H0000FF00",
        "outline_color": "&H00111111",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Popping lime green highlights for podcasts and high-energy content.",
    },
    "bold_white": {
        "name": "Bold Clean White",
        "font_name": "Montserrat ExtraBold",
        "font_size": 36,
        "primary_color": "&H00E0E0E0",
        "highlight_color": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "outline_width": 3,
        "shadow_width": 1,
        "margin_v": 240,
        "description": "Minimalist sleek aesthetic for business and educational shorts.",
    },
    "cyberpunk_cyan": {
        "name": "Cyberpunk Cyan",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00FFFF00",
        "highlight_color": "&H00FF00FF",
        "outline_color": "&H00050515",
        "outline_width": 4,
        "shadow_width": 3,
        "margin_v": 240,
        "description": "Futuristic gaming vibe with glowing cyan & hot magenta accents.",
    },
    "tiktok_pop": {
        "name": "TikTok Pop Red-Yellow",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H0000FFFF",
        "highlight_color": "&H000022FF",
        "outline_color": "&H00000000",
        "outline_width": 4,
        "shadow_width": 2,
        "margin_v": 230,
        "description": "Punchy style used across top TikTok comedy & storytelling creators.",
    },
    "fire_red": {
        "name": "Fire Red Flame",
        "font_name": "Impact",
        "font_size": 42,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H000033FF",
        "outline_color": "&H00000000",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Intense dramatic tone for debates and heated moments.",
    },
    "retro_vaporwave": {
        "name": "Retro Vaporwave",
        "font_name": "Trebuchet MS",
        "font_size": 38,
        "primary_color": "&H00FFB0E0",
        "highlight_color": "&H00FFFF00",
        "outline_color": "&H00330033",
        "outline_width": 3,
        "shadow_width": 3,
        "margin_v": 250,
        "description": "80s synthwave & aesthetic pastel palette with purple shadow.",
    },
    "mrbeast_impact": {
        "name": "MrBeast Impact Yellow",
        "font_name": "Impact",
        "font_size": 46,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H0000E6FF",
        "outline_color": "&H00000000",
        "outline_width": 5,
        "shadow_width": 3,
        "margin_v": 260,
        "description": "Heavy Impact lettering with ultra-thick border for maximum CTR.",
    },
    "pastel_pink": {
        "name": "Pastel Pink Aesthetic",
        "font_name": "Arial",
        "font_size": 36,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H00D8A4FF",
        "outline_color": "&H002E1B33",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 230,
        "description": "Soft aesthetic look for beauty, lifestyle, and vlog creators.",
    },
    "minimalist_dark": {
        "name": "Minimalist Dark Box",
        "font_name": "Helvetica",
        "font_size": 34,
        "primary_color": "&H00F0F0F0",
        "highlight_color": "&H004DF8FF",
        "outline_color": "&H00000000",
        "outline_width": 2,
        "shadow_width": 0,
        "margin_v": 220,
        "description": "Clean dark boxed lower-third style for documentary clips.",
    },
    "comic_punch": {
        "name": "Comic Book Punch",
        "font_name": "Impact",
        "font_size": 42,
        "primary_color": "&H0000FFFF",
        "highlight_color": "&H00FFFFFF",
        "outline_color": "&H00000000",
        "outline_width": 4,
        "shadow_width": 4,
        "margin_v": 250,
        "description": "Dynamic comic-book feel for anime and reaction channels.",
    },
    "golden_hour": {
        "name": "Golden Hour Amber",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00E6F0FF",
        "highlight_color": "&H0010A5FF",
        "outline_color": "&H001A1005",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Warm cinematic sunset tones for cinematic vlogs.",
    },
    "electric_purple": {
        "name": "Electric Purple Violet",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H00FF33B8",
        "outline_color": "&H001B0324",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Striking neon violet highlight with sharp dark border.",
    },
    "sunset_orange": {
        "name": "Sunset Coral Orange",
        "font_name": "Impact",
        "font_size": 42,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H00147BFF",
        "outline_color": "&H000D0905",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Energetic sunset coral glow for Instagram Reels.",
    },
    "matrix_green": {
        "name": "Matrix Digital Green",
        "font_name": "Courier New",
        "font_size": 38,
        "primary_color": "&H0000CC00",
        "highlight_color": "&H0080FF80",
        "outline_color": "&H00001500",
        "outline_width": 3,
        "shadow_width": 1,
        "margin_v": 230,
        "description": "Monospace hacker look for tech tutorials & code reviews.",
    },
    "deep_blue": {
        "name": "Ice Blue Arctic",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H00FFAA33",
        "outline_color": "&H00241005",
        "outline_width": 3,
        "shadow_width": 2,
        "margin_v": 240,
        "description": "Clean arctic blue styling with sharp contrast against skin tones.",
    },
    "boxed_karaoke": {
        "name": "Boxed Pill Karaoke",
        "font_name": "Arial",
        "font_size": 38,
        "primary_color": "&H00DDDDDD",
        "highlight_color": "&H0000E5FF",
        "outline_color": "&H00000000",
        "outline_width": 1,
        "shadow_width": 0,
        "border_style": 3,
        "margin_v": 220,
        "description": "Dark rounded bounding box ensuring 100% legibility on any background.",
    },
    "glitch_shadow": {
        "name": "Glitch Cyan Shadow",
        "font_name": "Arial Black",
        "font_size": 40,
        "primary_color": "&H00FFFFFF",
        "highlight_color": "&H0030E0FF",
        "outline_color": "&H00FF00AA",
        "outline_width": 3,
        "shadow_width": 4,
        "margin_v": 240,
        "description": "Chromatic aberration glitch aesthetic for fast gaming clips.",
    },
    "elegant_serif": {
        "name": "Editorial Luxury Serif",
        "font_name": "Georgia",
        "font_size": 36,
        "primary_color": "&H00F5F5F5",
        "highlight_color": "&H006BD3FF",
        "outline_color": "&H001C1C1C",
        "outline_width": 2,
        "shadow_width": 1,
        "margin_v": 230,
        "description": "Upscale editorial serif typography for luxury lifestyle.",
    },
    "high_contrast": {
        "name": "Accessibility Hyper-Contrast",
        "font_name": "Arial Black",
        "font_size": 42,
        "primary_color": "&H00000000",
        "highlight_color": "&H000000FF",
        "outline_color": "&H0000FFFF",
        "outline_width": 5,
        "shadow_width": 0,
        "margin_v": 250,
        "description": "Extreme readability inverted yellow/black high-contrast design.",
    },
    "monochrome_chic": {
        "name": "Monochrome Chic Grayscale",
        "font_name": "Helvetica",
        "font_size": 38,
        "primary_color": "&H00888888",
        "highlight_color": "&H00FFFFFF",
        "outline_color": "&H00111111",
        "outline_width": 3,
        "shadow_width": 1,
        "margin_v": 235,
        "description": "Minimalist grayscale transition for fashion and art shorts.",
    },
    "gaming_rgb": {
        "name": "Gamer RGB Lime & Violet",
        "font_name": "Impact",
        "font_size": 44,
        "primary_color": "&H0000FF80",
        "highlight_color": "&H00FF20B0",
        "outline_color": "&H00000000",
        "outline_width": 4,
        "shadow_width": 3,
        "margin_v": 255,
        "description": "Ultra-saturated RGB lighting style for gaming shorts.",
    },
}


def get_available_presets() -> List[Dict[str, Any]]:
    """Returns a list of all available caption presets with metadata for UI dropdowns."""
    presets = []
    for preset_id, info in CAPTION_PRESETS.items():
        presets.append({
            "id": preset_id,
            "name": info["name"],
            "description": info.get("description", ""),
            "font_name": info.get("font_name", "Arial Black"),
            "font_size": info.get("font_size", 26),
            "primary_color": info.get("primary_color", "&H00FFFFFF"),
            "highlight_color": info.get("highlight_color", "&H0000FFFF"),
        })
    return presets